import Head from 'next/head'
// import Image from 'next/image'
import 'semantic-ui-css/semantic.min.css'
// import styles from '../styles/Home.module.css'  // className={styles.container}

export default function Home() {

  return (
    <div>
      <Head>
        <title>My APP [Next]</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  )
}
